package demo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private int age;
   private java.lang.Boolean drivingPermit;

   public Person()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public int getAge()
   {
      return this.age;
   }

   public void setAge(int age)
   {
      this.age = age;
   }

   public java.lang.Boolean getDrivingPermit()
   {
      return this.drivingPermit;
   }

   public void setDrivingPermit(java.lang.Boolean drivingPermit)
   {
      this.drivingPermit = drivingPermit;
   }

   public Person(java.lang.String name, int age,
         java.lang.Boolean drivingPermit)
   {
      this.name = name;
      this.age = age;
      this.drivingPermit = drivingPermit;
   }

}